name: Build & Debug GainVintage VST3 (macOS)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install CMake
        run: brew install cmake

      - name: Build Plugin
        run: cargo xtask bundle -p gain-vintage --release

      - name: Upload Build Artifact for Debugging
        uses: actions/upload-artifact@v3
        with:
          name: GainVintage-Build-Debug
          path: target/bundled/gain-vintage.vst3
