name: Release GainVintage VST3

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Plugin (VST3)
        run: cargo xtask bundle -p gain-vintage --release

      - name: Upload VST3 as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/bundled/gain-vintage.vst3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
C